name : CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
